### ISSUE TITLE
Fix incorrect docs for ApiError subclasses

### ISSUE THREAD

**Issue by Dromin** [OpenWebslides/openwebslides-frontend#107]

**Comment by Dromin** [comment]
Also, would it be possible to use more descriptive class names? For example, I'd have a hard time figuring out what the problem is if a `ValidationError` is thrown. What does not validate and why? Same with `ForbiddenError` etc.

**Comment by floriandejonckheere** [comment]
`ApiError`s are parsed directly from the server. Subsequently, `ForbiddenError` literally means a HTTP 403 Forbidden from the server. `ValidationError` is derived from the [JSON-API](http://jsonapi.org/) standard, and means that one or more fields failed to validate (as indicated by the HTTP 422 Unprocessable Entity status code).

I will add some comments to make this clear in the classes. ApiErrors should not leave the API sagas.
