### ISSUE TITLE
Page moves around strangely if viewport width is made smaller

### ISSUE THREAD

**Issue by Dromin** [OpenWebslides/openwebslides-frontend#16]
**Problem:** At certain breakpoints the page content jerks around and is no longer centered.

**Reproduce:** open random page that has a `Page` wrapper around it; slowly make viewport smaller. Easiest to see with elements that take the full page width (for example, the library, or the editor if you first wrap it in a `Page`).

**Comment by JasperDhaene** [comment]
Fixed in PR: Styling + Page rewrite #36
