### ISSUE TITLE
Invalid sign in regression

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/openwebslides-frontend#179]
When trying to sign in with invalid credentials, the console emits a `401 Unauthorized` error, and the ApiDimmer keeps spinning. No error messages are shown in the UI.

**Comment by Dromin** [comment]
Yes, I know 😅 That's because I temporarily had to take out all of the separate flash messages in order to automate them; see https://trello.com/c/K9AoG4N2 .
