### ISSUE TITLE
ESLint enforce destructuring

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/openwebslides-frontend#182]
Configure ESLint to enforce destructuring:

Prefer
```js
const { AuthWrapper } = platform.components;
```
Over
```js
const AuthWrapper = platform.components.AuthWrapper;
```

**Comment by Dromin** [comment]
That was turned off on purpose: https://github.com/OpenWebslides/openwebslides-frontend/blob/master/.eslintrc.js#L102
