### ISSUE TITLE
Change text edit shortcuts

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/openwebslides-frontend#231]
Change the CTRL+Left/Right shortcut on content item text edit for two reasons:
- Mac users cannot use this, they would have to use Command+Left/Right and this is not bound
- It overrides the functionality of jumping the cursor word by word in the input field

**Comment by Dromin** [comment]
Any suggestions for what to use instead?

**Comment by floriandejonckheere** [comment]
I suppose Tab/Shift-Tab would be the shortcut that breaks the user's expectation the least.

**Comment by floriandejonckheere** [comment]
Then again Tab/Shift-Tab is used in browsers for focus...

**Comment by floriandejonckheere** [comment]
Additional suggestion: use `react-keyboard-handler` instead of `if`'ing the event keys, since it does not exclude combined shortcuts. E.g. the following does not exclude 'Ctrl+Alt+Left'.

```js
if (event.key === 'ArrowLeft' && event.ctrlKey === true)
```

**Comment by Dromin** [comment]
> I suppose Tab/Shift-Tab would be the shortcut that breaks the user's expectation the least.

Any solution does need to involve the arrow keys, since arrow-up and arrow-down will be used in the future to move contentItems up and down. Simply tab / backwards tab won't be enough (and like you said, is used for moving the cursor between contentItems).

**Comment by Dromin** [comment]
I'm currently thinking a solution with two different 'modes' (i.e. editing mode and manipulation mode) might be best; that way the shortcuts for contentItem manipulation won't interfere with shortcuts for editing text.

**Comment by floriandejonckheere** [comment]
That might be a good idea, where the manipulation only happens if the editable content item is not active (i.e. no input box). I'm currently implementing select-by-arrow-keys functionality, I'll include this as well.

Summary of how you should be able to navigate:
Arrows and Tab to select content items (manipulation mode)
Ctrl+Arrows and Meta+Arrows to move content item (manipulation mode)
Enter to start editing content items (when in manipulation mode)
Enter to stop editing content items and enter a new paragraph (when in manipulation mode)
Escape to discard edits (when in editing mode)
