### ISSUE TITLE
Refactor module imports in FeedItem & ProfileCard components

### ISSUE THREAD

**Issue by Dromin** [OpenWebslides/openwebslides-frontend#25]
**Problem:** modules should only be imported as a whole, e.g. `import topics from 'modules/topics';`. (See [here](https://jaysoo.ca/2016/02/28/organizing-redux-application/) for more info about this.) In the FeedItem & ProfileCard components several parts of other modules are imported incorrectly.

Problem imports in FeedItem:
```
import { getDisplayNameAndEmailById } from 'modules/users/selectors';
import { getTitleById } from 'modules/topics/selectors';
import type { DisplayNameAndEmailType } from 'modules/users/model';
```

Problem imports in ProfileCard:
```
import SimpleList from 'modules/topics/components/SimpleList';
```

For an example of correct module imports, see `pages/components/TopicsPage.js`.

Additional note: after this issue is fixed, the `getTitleById` topic selector can be deleted (since I assume it was only added to avoid the naming conflict that would have been caused by incorrectly importing the `getById` selector from the topics module).

**Comment by JasperDhaene** [comment]
Solved in PR #53
