### ISSUE TITLE
Increase ESLint max line length

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/openwebslides-frontend#30]
Increase or disable the ESLint maximum line length

**Comment by Dromin** [comment]
What is the problem with the current line length? Are you having a specific issue or do you just not like it? I personally think the current line length is very practical because it allows putting two files side by side in the IDE and have them both still be readable.

**Comment by floriandejonckheere** [comment]
Specifically in tests, lines tend to be more than 80 or 100 characters without the need of refactoring or splitting them up. Ignoring this rule for test files would be a solution.

Besides, in my opinion the traditional limit of 80 characters seems hardly appropriate for modern standards. However, long lines are usually symptoms of bad code.

**Comment by floriandejonckheere** [comment]
I wasn't sure about the limit, because the ESLint default seems to be 80, and it's not overridden in `.eslintrc`.

For reference, in the [backend](https://github.com/OpenWebslides/openwebslides-backend/blob/master/.rubocop.yml#L13) the limit is 120 and the rule is disabled for all tests. I would suggest disabling this for tests in the frontend in general as well.

**Comment by Dromin** [comment]
`.eslintrc` extends the airbnb eslint config, so all rules that haven't been overriden are take from there.

I'll look into disabling `max-len` and maybe some other rules for tests files specifically.
