### ISSUE TITLE
Authorization redirection code

### ISSUE THREAD

**Issue by JasperDhaene** [OpenWebslides/openwebslides-frontend#52]
~Now displays profile of user 'jantje1234'~

Redirect to `/auth/signin` for authorized pages.

**Comment by floriandejonckheere** [comment]
Relevant [unmerged code](https://github.com/OpenWebslides/openwebslides-frontend/blob/feature-authentication-sagas/app/modules/authentication/components/forms/SigninForm.js#L52)
