### ISSUE TITLE
Readd Flow reducer action type check

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/openwebslides-frontend#62]
Readd this piece of code back to reducers:

```
default:
  // Type error when not all action.type cases are handled.
  // eslint-disable-next-line no-unused-expressions
  (action: empty);
```

**Comment by Dromin** [comment]
While you're on it, perhaps change that comment to `Make sure a flow type error is thrown if not all action.type cases are handled` since the original comment was appearantly not very clear.
